CREATE TABLE IF NOT EXISTS stats (
    klub_id character varying(3) NOT NULL,
    sezon_id character varying(9) NOT NULL,
    mecze_dom integer DEFAULT 0 NOT NULL,
    zwy_dom integer DEFAULT 0 NOT NULL,
    rem_dom integer DEFAULT 0 NOT NULL,
    por_dom integer DEFAULT 0 NOT NULL,
    gole_zdob_dom integer DEFAULT 0 NOT NULL,
    gole_stra_dom integer DEFAULT 0 NOT NULL,
    mecze_wyj integer DEFAULT 0 NOT NULL,
    zwy_wyj integer DEFAULT 0 NOT NULL,
    rem_wyj integer DEFAULT 0 NOT NULL,
    por_wyj integer DEFAULT 0 NOT NULL,
    gole_zdob_wyj integer DEFAULT 0 NOT NULL,
    gole_stra_wyj integer DEFAULT 0 NOT NULL,
    PRIMARY KEY (klub_id, sezon_id),
    CHECK (mecze_wyj = zwy_wyj + rem_wyj + por_wyj),
    CHECK (mecze_dom = zwy_dom + rem_dom + por_dom),
    CHECK (gole_stra_dom >= 0),
    CHECK (gole_stra_wyj >= 0),
    CHECK (gole_zdob_dom >= 0),
    CHECK (gole_zdob_wyj >= 0),
    CHECK (por_dom >= 0),
    CHECK (por_wyj >= 0),
    CHECK (rem_dom >= 0),
    CHECK (rem_wyj >= 0),
    CHECK (zwy_dom >= 0),
    CHECK (zwy_wyj >= 0)
);

